var scoreTable = [
  ['Ones', 0],
  ['Twos', 0],
  ['Threes',  0],
  ['Fours', 0],
  ['Fives', 0],
  ['Sixes', 0],
  ['Up Bonus', 0],
  ['Up Sum', 0],
  ['Pair', 0],
  ['Two Pairs', 0],
  ['Three Of A Kind', 0],
  ['Small Street', 0],
  ['Big Street', 0],
  ['Nothing', 0],
  ['Middle Bonus', 0],
  ['Middle Sum', 0],
  ['Odds', 0],
  ['Evens', 0],
  ['Full House', 0],
  ['Four Of A Kind', 0],
  ['Poker', 0],
  ['Chance', 0],
  ['Down Bonus', 0],
  ['Down Sum', 0],
  ['Overall Sum', 0]
];
